#!/bin/bash
#
# \author  Alexander Boettcher

set -e # exit immediately on error

if [ ! -d $GENODE_DIR/repos ]; then
	echo "Directory seems not to contain Genode sources - exit"
	echo "\$GENODE_DIR: '$GENODE_DIR'"
	exit
fi

MAKE="${MAKE:="make"} --quiet"

set -u # treat unset variables as error

cd $GENODE_DIR

GRUB2_PORT_DIR=$($GENODE_DIR/tool/ports/current grub2)

GRUB2_DIR=/tmp/tmp.genode_grub2

GRUB2_KEEP_TMP=1

if [ ! -d $GRUB2_DIR ]; then
	GRUB2_DIR=$(mktemp -d)
fi

GRUB2_DIR_SRC=$GRUB2_DIR/grub.git

if [ ! -d $GRUB2_DIR_SRC ]; then
	#git clone git://git.savannah.gnu.org/grub.git $GRUB2_DIR/grub.git
	# ae94b97be2b81b625d6af6654d3ed79078b50ff6 (tag: grub-2.06)
	#genode_uefi version:
	#   commit 2bda5a81db1e0cb113a7cf69d283e3e2635189e8
	#  based on grub-2.06
	# genode_bios version:
	#   commit 2bda5a81db1e0cb113a7cf69d283e3e2635189e8
	#  based on grub-2.06

	git clone https://github.com/alex-ab/grub.git $GRUB2_DIR_SRC
	cd $GRUB2_DIR_SRC && git checkout origin/genode_bios_206 -b genode_bios_206
fi
if [ ! -f $GRUB2_DIR_SRC/configure ]; then
	cd $GRUB2_DIR_SRC && ./bootstrap
fi

GRUB2_MODULES_COMMON="part_gpt multiboot multiboot2 gzio configfile"
GRUB2_MODULES_UEFI="fat ext2 efi_uga efi_gop gfxterm_background png regexp"

#
# UEFI 64 bit version
#
GRUB2_DIR_UEFI_64=$GRUB2_DIR/64_efi
GRUB2_DIR_UEFI_64_INSTALL=$GRUB2_DIR_UEFI_64/binary
mkdir -p $GRUB2_DIR_UEFI_64_INSTALL

if [ ! -f $GRUB2_DIR_UEFI_64/config.h ]; then
	cd $GRUB2_DIR_UEFI_64 && $GRUB2_DIR_SRC/configure --quiet --prefix=$GRUB2_DIR_UEFI_64_INSTALL --with-platform=efi --target=x86_64
fi
$MAKE -C $GRUB2_DIR_UEFI_64 install

$GRUB2_DIR_UEFI_64_INSTALL/bin/grub-mkimage -O x86_64-efi -d $GRUB2_DIR_UEFI_64_INSTALL/lib/grub/x86_64-efi -o $GRUB2_DIR/grub2_64.efi $GRUB2_MODULES_COMMON $GRUB2_MODULES_UEFI -p "/boot/grub"
$GRUB2_DIR_UEFI_64_INSTALL/bin/grub-mkimage -O x86_64-efi -d $GRUB2_DIR_UEFI_64_INSTALL/lib/grub/x86_64-efi -o $GRUB2_DIR/grub2_64net.efi tftp efinet multiboot2 gzio configfile -p "/tftpboot"


#
# UEFI 32 bit version
#
GRUB2_DIR_UEFI_32=$GRUB2_DIR/32_efi
GRUB2_DIR_UEFI_32_INSTALL=$GRUB2_DIR_UEFI_32/binary
mkdir -p $GRUB2_DIR_UEFI_32_INSTALL

if [ ! -f $GRUB2_DIR_UEFI_32/config.h ]; then
	cd $GRUB2_DIR_UEFI_32 && $GRUB2_DIR_SRC/configure --quiet --prefix=$GRUB2_DIR_UEFI_32_INSTALL --with-platform=efi --target=i386
fi
$MAKE -C $GRUB2_DIR_UEFI_32 install

$GRUB2_DIR_UEFI_32_INSTALL/bin/grub-mkimage -O i386-efi -d $GRUB2_DIR_UEFI_32_INSTALL/lib/grub/i386-efi -o $GRUB2_DIR/grub2_32.efi $GRUB2_MODULES_COMMON $GRUB2_MODULES_UEFI -p "/boot/grub"


#
# BIOS version
#
GRUB2_DIR_BIOS=$GRUB2_DIR/32_pc
GRUB2_DIR_BIOS_INSTALL=$GRUB2_DIR_BIOS/binary
mkdir -p $GRUB2_DIR_BIOS_INSTALL

if [ ! -f $GRUB2_DIR_BIOS/config.h ]; then
	cd $GRUB2_DIR_BIOS && $GRUB2_DIR_SRC/configure --quiet --prefix=$GRUB2_DIR_BIOS_INSTALL --with-platform=pc
fi
$MAKE -C $GRUB2_DIR_BIOS install

$GRUB2_DIR_BIOS_INSTALL/bin/grub-mkimage -O i386-pc -d $GRUB2_DIR_BIOS_INSTALL/lib/grub/i386-pc -o $GRUB2_DIR/bios.img iso9660 biosdisk -p "/boot/grub"
cat $GRUB2_DIR_BIOS_INSTALL/lib/grub/i386-pc/cdboot.img $GRUB2_DIR/bios.img > $GRUB2_DIR/eltorito.img
cat $GRUB2_DIR_BIOS_INSTALL/lib/grub/i386-pc/boot.img $GRUB2_DIR/bios.img > $GRUB2_DIR/embedded.img


#
# Copy bootloader binaries to genode tool directory
#
if [ ! -d $GRUB2_DIR/grub2 ]; then
	mkdir $GRUB2_DIR/grub2
else
	rm $GRUB2_DIR/grub2/*
fi

# searched for and loaded by GRUB2 when part of ISO (--image/iso in Genode)
ISO_MODULES="acpi boot bufio crypto datetime extcmd gcry_crc gettext gzio linux lsapm mmap multiboot multiboot2 net normal priority_queue regexp relocator terminal vbe video_fb video"
for file in $ISO_MODULES
do
	cp $GRUB2_DIR_BIOS_INSTALL/lib/grub/i386-pc/$file.mod $GRUB2_DIR/grub2/$file.mod
done

cp $GRUB2_DIR/eltorito.img $GRUB2_DIR/grub2/.
cp $GRUB2_DIR/embedded.img $GRUB2_DIR/grub2/.

# UEFI
cp $GRUB2_DIR/grub2_32.efi $GRUB2_DIR/grub2/.
cp $GRUB2_DIR/grub2_64.efi $GRUB2_DIR/grub2/.
cp $GRUB2_DIR/grub2_64net.efi $GRUB2_DIR/grub2/.

# tar
tar cJfC $GRUB2_DIR/grub2-tmp.tar.xz $GRUB2_DIR grub2
SHA1SUM=$(sha1sum $GRUB2_DIR/grub2-tmp.tar.xz | cut -f1 -d" ")

mv $GRUB2_DIR/grub2-tmp.tar.xz $GRUB2_DIR/grub2-$SHA1SUM.tar.xz

#
# Cleanup if requested
#
if [ $GRUB2_KEEP_TMP -eq 1 ]; then
	echo ""
	echo "keep temporary directory $GRUB2_DIR"
	echo " grub2-$SHA1SUM.tar.xz"
	echo "contains all the GRUB2 binaries"
else
	rm -rf $GRUB2_DIR
fi

